# Generated by Django 5.0.6 on 2024-11-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_user',
            field=models.BooleanField(default=False),
        ),
    ]
