# Generated by Django 5.0.6 on 2024-08-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['invited'], name='invited_idx'),
        ),
        migrations.AddIndex(
            model_name='invite',
            index=models.Index(fields=['game'], name='game_idx'),
        ),
    ]
