# Generated by Django 5.0.6 on 2024-11-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_alter_user_oauth_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_phase',
            field=models.CharField(choices=[('None', 'None'), ('quarters', 'quarters'), ('semis', 'semis'), ('finals', 'finals')], default='semis'),
        ),
    ]
