# Generated by Django 5.0.6 on 2025-01-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_tournament_tournament_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('pong', 'Pong'), ('osnier', 'Osnier')], default='custom'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='genre',
            field=models.CharField(choices=[('pong', 'Pong'), ('osnier', 'Osnier')], default='pong'),
        ),
    ]
