# Generated by Django 5.0.6 on 2025-01-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_game_genre_tournament_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('pong', 'Pong'), ('osnier', 'Osnier')], default='pong'),
        ),
    ]
