version : '3.8'

services:
    postgres:
      build:
        context: ./postgres
        dockerfile: Dockerfile
        args:
          PG_ROOT_PASSWORD : ${PG_ROOT_PASSWORD}
          PG_USERNAME : ${PG_USERNAME}
          PG_USER_PASSWORD : ${PG_USER_PASSWORD}
          PG_DB_NAME : ${PG_DB_NAME}
      image: postgres:pong
      volumes:
        - postgres_volume:/var/lib/postgresql/data
      networks:
        - pong
      container_name: postgres
      restart: always
    pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      networks:
        - pong
      ports:
        - "9000:80"
      container_name: pgadmin
      depends_on:
        - postgres
      restart: always
    django:
      build:
        context: ./django
        dockerfile: Dockerfile
        args:
          PG_USERNAME : ${PG_USERNAME}
          PG_USER_PASSWORD : ${PG_USER_PASSWORD}
          PG_DB_NAME : ${PG_DB_NAME}
      image: django:pong
      volumes:
        - django_volume:/usr/backend
      depends_on:
        - postgres
      networks:
        - pong
      ports:
        - "8000:8000"
      container_name: django
      restart : always

networks:
  pong:
    driver: bridge
    name: pong

volumes:
  postgres_volume:
  django_volume:
    name: django_volume
    driver: local
    driver_opts:
      type: none
      device: ../backend
      o: bind

